name: CI

on:
  pull_request:
  push:
    branches: [ main, "**/*" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip install uvicorn
      - name: Run unit tests
        env:
          PYTHONPATH: src:.
        run: |
          pytest -q

  smoke:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install runtime deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install uvicorn requests
      - name: Launch server
        env:
          PYTHONPATH: src:.
          # Leave OMP_SIG_MODE unset (defaults to "off"); tests set it explicitly.
        run: |
          python -m uvicorn omp_ref_server.main:app --host 127.0.0.1 --port 8000 &
          echo $! > uvicorn.pid

      - name: Wait for server
        run: |
          for i in {1..30}; do
            curl -fsS http://127.0.0.1:8000/objects >/dev/null 2>&1 && exit 0
            sleep 1
          done
          echo "Server did not start in time" >&2
          exit 1

      - name: Smoke GET /objects
        run: |
          curl -fsS http://127.0.0.1:8000/objects | tee /dev/stderr

      - name: Stop server
        if: always()
        run: |
          if [ -f uvicorn.pid ]; then kill $(cat uvicorn.pid) || true; fi
